[package]
name = "skebe"
version = "0.1.0"
authors = [ "misonomi <misonomi0612@gmail.com>" ]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.0", features = ["json"] }
egg-mode = "0.15.0"
serde = "1.0.118"
tokio = { version = "1.0.1", features = ["full"] }
tokio-compat-02 = "0.2"